version: "3.4"

services:
  deephaven:
    image: deephaven-examples/deephaven-plus-cryptowatch:latest
    ports:
      - "${DEEPHAVEN_PORT:-10000}:10000"
    volumes:
      - ./data:/data
    environment:
      - START_OPTS=-Xmx4g -Ddeephaven.application.dir=/data/app.d
